
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftMENORQUEIGUALleftINCREMENTCOMA DERCORCHET DERPARENT FOR ID IGUAL INCREMENT INT ITERADOR IZQCORCHET IZQPARENT MENORQUE NUMERO OUT PRINTLN PUNTO PUNTOCOMA STRING SYSTEM\n    program : statement\n            | program statement\n    \n    statement : assignment_statement\n              | comparison_statement\n              | for_loop_statement\n              | print_statement\n    \n    assignment_statement : ID IGUAL expression\n                         | ID IGUAL INT\n                         | ID IGUAL STRING\n    \n    comparison_statement : expression MENORQUE expression\n                         | expression IGUAL expression \n    \n    for_loop_statement : FOR IZQPARENT assignment_statement PUNTOCOMA comparison_statement PUNTOCOMA assignment_statement DERPARENT  print_statement \n    \n    print_statement : SYSTEM PUNTO OUT PUNTO PRINTLN IZQPARENT expression DERPARENT PUNTOCOMA\n    \n    expression : ID\n               | INT\n               | STRING\n    \n    string_expression : STRING\n                      | STRING PUNTO INT\n                      | STRING PUNTO ID\n    '
    
_lr_action_items = {'ID':([0,1,2,3,4,5,6,9,10,13,14,15,16,17,19,20,21,22,23,24,28,32,33,38,39,],[7,7,-1,-3,-4,-5,-6,-15,-16,-2,19,19,19,26,-14,-7,-8,-9,-10,-11,19,26,19,-12,-13,]),'FOR':([0,1,2,3,4,5,6,9,10,13,19,20,21,22,23,24,38,39,],[11,11,-1,-3,-4,-5,-6,-15,-16,-2,-14,-7,-8,-9,-10,-11,-12,-13,]),'SYSTEM':([0,1,2,3,4,5,6,9,10,13,19,20,21,22,23,24,36,38,39,],[12,12,-1,-3,-4,-5,-6,-15,-16,-2,-14,-7,-8,-9,-10,-11,12,-12,-13,]),'INT':([0,1,2,3,4,5,6,9,10,13,14,15,16,19,20,21,22,23,24,28,33,38,39,],[9,9,-1,-3,-4,-5,-6,-15,-16,-2,21,9,9,-14,-7,-8,-9,-10,-11,9,9,-12,-13,]),'STRING':([0,1,2,3,4,5,6,9,10,13,14,15,16,19,20,21,22,23,24,28,33,38,39,],[10,10,-1,-3,-4,-5,-6,-15,-16,-2,22,10,10,-14,-7,-8,-9,-10,-11,10,10,-12,-13,]),'$end':([1,2,3,4,5,6,9,10,13,19,20,21,22,23,24,38,39,],[0,-1,-3,-4,-5,-6,-15,-16,-2,-14,-7,-8,-9,-10,-11,-12,-13,]),'IGUAL':([7,8,9,10,19,26,],[14,16,-15,-16,-14,14,]),'MENORQUE':([7,8,9,10,19,],[-14,15,-15,-16,-14,]),'PUNTOCOMA':([9,10,19,20,21,22,23,24,25,30,37,],[-15,-16,-14,-7,-8,-9,-10,-11,28,32,39,]),'DERPARENT':([9,10,19,20,21,22,34,35,],[-15,-16,-14,-7,-8,-9,36,37,]),'IZQPARENT':([11,31,],[17,33,]),'PUNTO':([12,27,],[18,29,]),'OUT':([18,],[27,]),'PRINTLN':([29,],[31,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement':([0,1,],[2,13,]),'assignment_statement':([0,1,17,32,],[3,3,25,34,]),'comparison_statement':([0,1,28,],[4,4,30,]),'for_loop_statement':([0,1,],[5,5,]),'print_statement':([0,1,36,],[6,6,38,]),'expression':([0,1,14,15,16,28,33,],[8,8,20,23,24,8,35,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement','program',1,'p_program','analizador_sintactico.py',36),
  ('program -> program statement','program',2,'p_program','analizador_sintactico.py',37),
  ('statement -> assignment_statement','statement',1,'p_statement','analizador_sintactico.py',43),
  ('statement -> comparison_statement','statement',1,'p_statement','analizador_sintactico.py',44),
  ('statement -> for_loop_statement','statement',1,'p_statement','analizador_sintactico.py',45),
  ('statement -> print_statement','statement',1,'p_statement','analizador_sintactico.py',46),
  ('assignment_statement -> ID IGUAL expression','assignment_statement',3,'p_assignment_statement','analizador_sintactico.py',52),
  ('assignment_statement -> ID IGUAL INT','assignment_statement',3,'p_assignment_statement','analizador_sintactico.py',53),
  ('assignment_statement -> ID IGUAL STRING','assignment_statement',3,'p_assignment_statement','analizador_sintactico.py',54),
  ('comparison_statement -> expression MENORQUE expression','comparison_statement',3,'p_comparison_statement','analizador_sintactico.py',60),
  ('comparison_statement -> expression IGUAL expression','comparison_statement',3,'p_comparison_statement','analizador_sintactico.py',61),
  ('for_loop_statement -> FOR IZQPARENT assignment_statement PUNTOCOMA comparison_statement PUNTOCOMA assignment_statement DERPARENT print_statement','for_loop_statement',9,'p_for_loop_statement','analizador_sintactico.py',67),
  ('print_statement -> SYSTEM PUNTO OUT PUNTO PRINTLN IZQPARENT expression DERPARENT PUNTOCOMA','print_statement',9,'p_print_statement','analizador_sintactico.py',73),
  ('expression -> ID','expression',1,'p_expression','analizador_sintactico.py',79),
  ('expression -> INT','expression',1,'p_expression','analizador_sintactico.py',80),
  ('expression -> STRING','expression',1,'p_expression','analizador_sintactico.py',81),
  ('string_expression -> STRING','string_expression',1,'p_string_expression','analizador_sintactico.py',87),
  ('string_expression -> STRING PUNTO INT','string_expression',3,'p_string_expression','analizador_sintactico.py',88),
  ('string_expression -> STRING PUNTO ID','string_expression',3,'p_string_expression','analizador_sintactico.py',89),
]
